-- Author Lalitha Viswanathan
-- caMOD 3.0
-- Truncate tables
TRUNCATE TABLE JACKSON_LAB_TMP2;
TRUNCATE TABLE ZSTG_AGENT;
TRUNCATE TABLE ZSTG_AGENTNAMES_TRIMMED;
TRUNCATE TABLE ZSTG_METASTASES;
TRUNCATE TABLE ZSTG_REFERENCE;
TRUNCATE TABLE ZSTG_TUMOR;
TRUNCATE TABLE ZSTG_TUMOR_AGENT;
TRUNCATE TABLE ZSTG_TUMOR_REF;
TRUNCATE TABLE ZSTG_TUMOR_AGENTNAME_COMBINED;
TRUNCATE TABLE ZSTG_METASTASES_COMBINED;
TRUNCATE TABLE ZSTG_TUMOR_REFERENCE_COMBINED;
TRUNCATE TABLE zstg_MAPPINGABSTUMOR;
EXIT;
