LOAD DATA 
 
INFILE "$DATA_DIR/TreatmentKey.txt"
REPLACE
INTO TABLE ZSTG_TUMOR_AGENTNAME_COMBINED 
REENABLE DISABLED_CONSTRAINTS  
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(TUMORKEY,
  AGENTNAME,
 AGENTTYPE
)
