LOAD DATA 
 
INFILE "$DATA_DIR/ReferenceKey.txt"
REPLACE
INTO TABLE ZSTG_TUMOR_REFERENCE_COMBINED 
REENABLE DISABLED_CONSTRAINTS  
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(TUMORKEY,
  JNUM_COMBINED
)
