LOAD DATA 
 
INFILE "$DATA_DIR/MetastasisKey.txt"
REPLACE
INTO TABLE ZSTG_METASTASES_COMBINED 
REENABLE DISABLED_CONSTRAINTS  
FIELDS TERMINATED BY "	"
TRAILING NULLCOLS
(TUMORKEY,
  METASTASISKEY,
   METASTASISORGAN
)
