LOAD DATA 
 
INFILE "$DATA_DIR/ModifiedTreatmentAgent.txt"
REPLACE
INTO TABLE ZSTG_agentnames_trimmed 
REENABLE DISABLED_CONSTRAINTS  
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(AGENTKEY,
  AGENTNAME 
)
