
create index AVAILLITY_RELEASE_DA on AVAILABILITY(RELEASE_DATE) PARALLEL NOLOGGING tablespace CAMOD;
create index AVAILLITY_MODIFIED_D on AVAILABILITY(MODIFIED_DATE) PARALLEL NOLOGGING tablespace CAMOD;
create index AVAILLITY_VISIBLE_TO on AVAILABILITY(VISIBLE_TO) PARALLEL NOLOGGING tablespace CAMOD;
create index AVAILLITY_ENTERED_DA on AVAILABILITY(ENTERED_DATE) PARALLEL NOLOGGING tablespace CAMOD;
create index AVAILLITY_AVAILABILI on AVAILABILITY(AVAILABILITY_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
