
create index DISEAEASE_NAME_ALTER on DISEASE(NAME_ALTERN_ENTRY) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_EXTERNAL_S on DISEASE(EXTERNAL_SOURCE) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_CONCEPT_CO on DISEASE(CONCEPT_CODE) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_NAME on DISEASE(NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_DISEASE_ID on DISEASE(DISEASE_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
