
create index DISEAEASE_NAME_ALTER_lwr on DISEASE(lower(NAME_ALTERN_ENTRY)) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_EXTERNAL_S_lwr on DISEASE(lower(EXTERNAL_SOURCE)) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_CONCEPT_CO_lwr on DISEASE(lower(CONCEPT_CODE)) PARALLEL NOLOGGING tablespace CAMOD;
create index DISEAEASE_NAME_lwr on DISEASE(lower(NAME)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
