
create index ENVIRCTOR_IS_INDUCED on ENVIRONMENTAL_FACTOR(IS_INDUCED_MUTATION_TRIGGER) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_COMMENTS on ENVIRONMENTAL_FACTOR(COMMENTS) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_NSC_NUMBER on ENVIRONMENTAL_FACTOR(NSC_NUMBER) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_CAS_NUMBER on ENVIRONMENTAL_FACTOR(CAS_NUMBER) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_NAME_ALTER on ENVIRONMENTAL_FACTOR(NAME_ALTERN_ENTRY) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_NAME on ENVIRONMENTAL_FACTOR(NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_TYPE_ALTER on ENVIRONMENTAL_FACTOR(TYPE_ALTERN_ENTRY) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_TYPE on ENVIRONMENTAL_FACTOR(TYPE) PARALLEL NOLOGGING tablespace CAMOD;
create index ENVIRCTOR_ENVIRONMEN on ENVIRONMENTAL_FACTOR(ENVIRONMENTAL_FACTOR_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
