
create index HISTOLOGY_TUMOR_INCI_lwr on HISTOPATHOLOGY(lower(TUMOR_INCIDENCE_RATE)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_MTB_ID_lwr on HISTOPATHOLOGY(lower(MTB_ID)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_DET_lwr on HISTOPATHOLOGY(lower(AGE_OF_DETECTION_UNIT)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_DET_lwr on HISTOPATHOLOGY(lower(AGE_OF_DETECTION)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_COMPARATIV_lwr on HISTOPATHOLOGY(lower(COMPARATIVE_DATA)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_VOLUME_OF__lwr on HISTOPATHOLOGY(lower(VOLUME_OF_TUMOR)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_WEIGHT_OF__lwr on HISTOPATHOLOGY(lower(WEIGHT_OF_TUMOR)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_MICROSCOPI_lwr on HISTOPATHOLOGY(lower(MICROSCOPIC_DESCRIPTION)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_ONS_lwr on HISTOPATHOLOGY(lower(AGE_OF_ONSET_UNIT)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_ONS_lwr on HISTOPATHOLOGY(lower(AGE_OF_ONSET)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_SURVIVAL_I_lwr on HISTOPATHOLOGY(lower(SURVIVAL_INFO)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_RELATIONAL_lwr on HISTOPATHOLOGY(lower(RELATIONAL_OPERATION)) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_GROSS_DESC_lwr on HISTOPATHOLOGY(lower(GROSS_DESCRIPTION)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
