
create index HISTOLOGY_TUMOR_INCI on HISTOPATHOLOGY(TUMOR_INCIDENCE_RATE) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_MTB_ID on HISTOPATHOLOGY(MTB_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_DET on HISTOPATHOLOGY(AGE_OF_DETECTION_UNIT) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_DET on HISTOPATHOLOGY(AGE_OF_DETECTION) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_PARENT_HIS on HISTOPATHOLOGY(PARENT_HISTOPATHOLOGY_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_ABS_CANCER on HISTOPATHOLOGY(ABS_CANCER_MODEL_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_GENETIC_AL on HISTOPATHOLOGY(GENETIC_ALTERATION_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_ORGAN_ID on HISTOPATHOLOGY(ORGAN_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_DISEASE_ID on HISTOPATHOLOGY(DISEASE_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_COMPARATIV on HISTOPATHOLOGY(COMPARATIVE_DATA) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_VOLUME_OF_ on HISTOPATHOLOGY(VOLUME_OF_TUMOR) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_WEIGHT_OF_ on HISTOPATHOLOGY(WEIGHT_OF_TUMOR) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_MICROSCOPI on HISTOPATHOLOGY(MICROSCOPIC_DESCRIPTION) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_ONS on HISTOPATHOLOGY(AGE_OF_ONSET_UNIT) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_AGE_OF_ONS on HISTOPATHOLOGY(AGE_OF_ONSET) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_SURVIVAL_I on HISTOPATHOLOGY(SURVIVAL_INFO) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_RELATIONAL on HISTOPATHOLOGY(RELATIONAL_OPERATION) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_GROSS_DESC on HISTOPATHOLOGY(GROSS_DESCRIPTION) PARALLEL NOLOGGING tablespace CAMOD;
create index HISTOLOGY_HISTOPATHO on HISTOPATHOLOGY(HISTOPATHOLOGY_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
