
create index IMAGEMAGE_URL_ALTERN on IMAGE(URL_ALTERN_ENTRY) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_COMMENTS on IMAGE(COMMENTS) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_ABS_CANCER on IMAGE(ABS_CANCER_MODEL_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_STAINING_M on IMAGE(STAINING_METHOD_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_URL on IMAGE(URL) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_DESCRIPTIO on IMAGE(DESCRIPTION) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_TITLE on IMAGE(TITLE) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_IMAGE_ID on IMAGE(IMAGE_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
