
create index IMAGEMAGE_URL_ALTERN_lwr on IMAGE(lower(URL_ALTERN_ENTRY)) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_COMMENTS_lwr on IMAGE(lower(COMMENTS)) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_URL_lwr on IMAGE(lower(URL)) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_DESCRIPTIO_lwr on IMAGE(lower(DESCRIPTION)) PARALLEL NOLOGGING tablespace CAMOD;
create index IMAGEMAGE_TITLE_lwr on IMAGE(lower(TITLE)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
