
create index JACKSTMP2_STRAIN_SYN on JACKSON_LAB_TMP2(STRAIN_SYNONYMS) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_REFERENCES on JACKSON_LAB_TMP2(REFERENCES) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_AGE_OF_DET on JACKSON_LAB_TMP2(AGE_OF_DETECTION) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_AGE_OF_ONS on JACKSON_LAB_TMP2(AGE_OF_ONSET) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TUMOR_FREQ on JACKSON_LAB_TMP2(TUMOR_FREQUENCY) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_REPRODUCTI on JACKSON_LAB_TMP2(REPRODUCTIVE_STATUS) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_SEX on JACKSON_LAB_TMP2(SEX) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_MTBIDS_OF_ on JACKSON_LAB_TMP2(MTBIDS_OF_METS) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_ORGAN_AFFE on JACKSON_LAB_TMP2(ORGAN_AFFECTED) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_ORGAN_KEY on JACKSON_LAB_TMP2(ORGAN_KEY) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TREATMENT_ on JACKSON_LAB_TMP2(TREATMENT_AGENTS) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TREATMENT_ on JACKSON_LAB_TMP2(TREATMENT_TYPE) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_GEN on JACKSON_LAB_TMP2(STRAIN_GENERAL_NOTE) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_TYP on JACKSON_LAB_TMP2(STRAIN_TYPES) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_NAM on JACKSON_LAB_TMP2(STRAIN_NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_KEY on JACKSON_LAB_TMP2(STRAIN_KEY) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TUMOR_NAME on JACKSON_LAB_TMP2(TUMOR_NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_MTB_ID on JACKSON_LAB_TMP2(MTB_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
