
create index JACKSTMP2_STRAIN_SYN_lwr on JACKSON_LAB_TMP2(lower(STRAIN_SYNONYMS)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_REFERENCES_lwr on JACKSON_LAB_TMP2(lower(REFERENCES)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_AGE_OF_DET_lwr on JACKSON_LAB_TMP2(lower(AGE_OF_DETECTION)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_AGE_OF_ONS_lwr on JACKSON_LAB_TMP2(lower(AGE_OF_ONSET)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TUMOR_FREQ_lwr on JACKSON_LAB_TMP2(lower(TUMOR_FREQUENCY)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_REPRODUCTI_lwr on JACKSON_LAB_TMP2(lower(REPRODUCTIVE_STATUS)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_SEX_lwr on JACKSON_LAB_TMP2(lower(SEX)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_MTBIDS_OF__lwr on JACKSON_LAB_TMP2(lower(MTBIDS_OF_METS)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_ORGAN_AFFE_lwr on JACKSON_LAB_TMP2(lower(ORGAN_AFFECTED)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_ORGAN_KEY_lwr on JACKSON_LAB_TMP2(lower(ORGAN_KEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TREATMENT__lwr on JACKSON_LAB_TMP2(lower(TREATMENT_AGENTS)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TREATMENT__lwr on JACKSON_LAB_TMP2(lower(TREATMENT_TYPE)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_GEN_lwr on JACKSON_LAB_TMP2(lower(STRAIN_GENERAL_NOTE)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_TYP_lwr on JACKSON_LAB_TMP2(lower(STRAIN_TYPES)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_NAM_lwr on JACKSON_LAB_TMP2(lower(STRAIN_NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_STRAIN_KEY_lwr on JACKSON_LAB_TMP2(lower(STRAIN_KEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_TUMOR_NAME_lwr on JACKSON_LAB_TMP2(lower(TUMOR_NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index JACKSTMP2_MTB_ID_lwr on JACKSON_LAB_TMP2(lower(MTB_ID)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
