
create index NOMENTURE_ABS_CANCER on NOMENCLATURE(ABS_CANCER_MODEL_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index NOMENTURE_NAME on NOMENCLATURE(NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index NOMENTURE_NOMENCLATU on NOMENCLATURE(NOMENCLATURE_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
