
create index ORGANRGAN_CONCEPT_CO on ORGAN(CONCEPT_CODE) PARALLEL NOLOGGING tablespace CAMOD;
create index ORGANRGAN_NAME on ORGAN(NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index ORGANRGAN_ORGAN_ID on ORGAN(ORGAN_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
