
create index PARTYARTY_NAME on PARTY(NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_IS_PRINCIP on PARTY(IS_PRINCIPAL_INVESTIGATOR) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_USERNAME on PARTY(USERNAME) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_LAST_NAME on PARTY(LAST_NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_MIDDLE_NAM on PARTY(MIDDLE_NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_FIRST_NAME on PARTY(FIRST_NAME) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_PARTY_TYPE on PARTY(PARTY_TYPE) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_PARTY_ID on PARTY(PARTY_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
