
create index PARTYARTY_NAME_lwr on PARTY(lower(NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_USERNAME_lwr on PARTY(lower(USERNAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_LAST_NAME_lwr on PARTY(lower(LAST_NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_MIDDLE_NAM_lwr on PARTY(lower(MIDDLE_NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_FIRST_NAME_lwr on PARTY(lower(FIRST_NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index PARTYARTY_PARTY_TYPE_lwr on PARTY(lower(PARTY_TYPE)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
