
create index PUBLITION_END_PAGE on PUBLICATION(END_PAGE) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_START_PAGE on PUBLICATION(START_PAGE) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_RGD_PUB_ID on PUBLICATION(RGD_PUB_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_COMMENTS on PUBLICATION(COMMENTS) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_ZFIN_PUB_I on PUBLICATION(ZFIN_PUB_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_PUBLICATIO on PUBLICATION(PUBLICATION_STATUS_ID) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_J_NUMBER on PUBLICATION(J_NUMBER) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_FIRST_TIME on PUBLICATION(FIRST_TIME_REPORTED) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_AUTHORS on PUBLICATION(AUTHORS) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_JOURNAL on PUBLICATION(JOURNAL) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_PMID on PUBLICATION(PMID) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_TITLE on PUBLICATION(TITLE) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_YEAR on PUBLICATION(YEAR) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_VOLUME on PUBLICATION(VOLUME) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_PUBLICATIO on PUBLICATION(PUBLICATION_ID) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
