
create index PUBLITION_END_PAGE_lwr on PUBLICATION(lower(END_PAGE)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_START_PAGE_lwr on PUBLICATION(lower(START_PAGE)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_RGD_PUB_ID_lwr on PUBLICATION(lower(RGD_PUB_ID)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_COMMENTS_lwr on PUBLICATION(lower(COMMENTS)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_ZFIN_PUB_I_lwr on PUBLICATION(lower(ZFIN_PUB_ID)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_J_NUMBER_lwr on PUBLICATION(lower(J_NUMBER)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_AUTHORS_lwr on PUBLICATION(lower(AUTHORS)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_JOURNAL_lwr on PUBLICATION(lower(JOURNAL)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_TITLE_lwr on PUBLICATION(lower(TITLE)) PARALLEL NOLOGGING tablespace CAMOD;
create index PUBLITION_VOLUME_lwr on PUBLICATION(lower(VOLUME)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
