
create index ZSTG_MMED_AGENTNAME on ZSTG_AGENTNAMES_TRIMMED(AGENTNAME) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_MMED_AGENTKEY on ZSTG_AGENTNAMES_TRIMMED(AGENTKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
