
create index ZSTG_INED_JNUM_COMBI_lwr on ZSTG_TUMOR_REFERENCE_COMBINED(lower(JNUM_COMBINED)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY_lwr on ZSTG_TUMOR_REFERENCE_COMBINED(lower(TUMORKEY)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
