
create index ZSTG_GENT_AGENTKEY_lwr on ZSTG_TUMOR_AGENT(lower(AGENTKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_TUMORKEY_lwr on ZSTG_TUMOR_AGENT(lower(TUMORKEY)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
