
create index ZSTG_GENT_AGENTNAMEM_lwr on ZSTG_AGENT(lower(AGENTNAMEMOD)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTNAME_lwr on ZSTG_AGENT(lower(AGENTNAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTTYPE_lwr on ZSTG_AGENT(lower(AGENTTYPE)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTKEY_lwr on ZSTG_AGENT(lower(AGENTKEY)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
