
create index ZSTG_INED_AGENTTYPE_lwr on ZSTG_TUMOR_AGENTNAME_COMBINED(lower(AGENTTYPE)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_AGENTNAME_lwr on ZSTG_TUMOR_AGENTNAME_COMBINED(lower(AGENTNAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY_lwr on ZSTG_TUMOR_AGENTNAME_COMBINED(lower(TUMORKEY)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
