
create index ZSTG_UMOR_HASIMAGES_lwr on ZSTG_TUMOR(lower(HASIMAGES)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_AGEOFDETEC_lwr on ZSTG_TUMOR(lower(AGEOFDETECTION)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_AGEOFONSET_lwr on ZSTG_TUMOR(lower(AGEOFONSET)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_TUMORFREQU_lwr on ZSTG_TUMOR(lower(TUMORFREQUENCY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_REPRODUCTI_lwr on ZSTG_TUMOR(lower(REPRODUCTIVESTATUS)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_SEX_lwr on ZSTG_TUMOR(lower(SEX)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_ORGANAFFEC_lwr on ZSTG_TUMOR(lower(ORGANAFFECTED)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_ORGANKEY_lwr on ZSTG_TUMOR(lower(ORGANKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINGENE_lwr on ZSTG_TUMOR(lower(STRAINGENERALNOTE)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINTYPE_lwr on ZSTG_TUMOR(lower(STRAINTYPES)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINNAME_lwr on ZSTG_TUMOR(lower(STRAINNAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINKEY_lwr on ZSTG_TUMOR(lower(STRAINKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_TUMORNAME_lwr on ZSTG_TUMOR(lower(TUMORNAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_TUMORKEY_lwr on ZSTG_TUMOR(lower(TUMORKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_TUMORID_lwr on ZSTG_TUMOR(lower(TUMORID)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
