
create index ZSTG_GENT_AGENTNAMEM on ZSTG_AGENT(AGENTNAMEMOD) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTNAME on ZSTG_AGENT(AGENTNAME) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTTYPE on ZSTG_AGENT(AGENTTYPE) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_AGENTKEY on ZSTG_AGENT(AGENTKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
