
create index ZSTG_GENT_AGENTKEY on ZSTG_TUMOR_AGENT(AGENTKEY) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_GENT_TUMORKEY on ZSTG_TUMOR_AGENT(TUMORKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
