
create index ZSTG_INED_JNUM_COMBI on ZSTG_TUMOR_REFERENCE_COMBINED(JNUM_COMBINED) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY on ZSTG_TUMOR_REFERENCE_COMBINED(TUMORKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
