
create index ZSTG_INED_METASTASIS on ZSTG_METASTASES_COMBINED(METASTASISORGAN) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_METASTASIS on ZSTG_METASTASES_COMBINED(METASTASISKEY) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY on ZSTG_METASTASES_COMBINED(TUMORKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
