
create index ZSTG_INED_METASTASIS_lwr on ZSTG_METASTASES_COMBINED(lower(METASTASISORGAN)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_METASTASIS_lwr on ZSTG_METASTASES_COMBINED(lower(METASTASISKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY_lwr on ZSTG_METASTASES_COMBINED(lower(TUMORKEY)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
