
create index ZSTG_INED_AGENTTYPE on ZSTG_TUMOR_AGENTNAME_COMBINED(AGENTTYPE) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_AGENTNAME on ZSTG_TUMOR_AGENTNAME_COMBINED(AGENTNAME) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_INED_TUMORKEY on ZSTG_TUMOR_AGENTNAME_COMBINED(TUMORKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
