
create index ZSTG_ASES_METASTASIS on ZSTG_METASTASES(METASTASISORGAN) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_ASES_METASTASIS on ZSTG_METASTASES(METASTASISKEY) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_ASES_TUMORKEY on ZSTG_METASTASES(TUMORKEY) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
