
create index ZSTG_UMOR_TREATMENTA_lwr on ZSTG_MAPPINGABSTUMOR(lower(TREATMENTAGENTS)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_TREATMENTT_lwr on ZSTG_MAPPINGABSTUMOR(lower(TREATMENTTYPES)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINTYPE_lwr on ZSTG_MAPPINGABSTUMOR(lower(STRAINTYPES)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAIN_lwr on ZSTG_MAPPINGABSTUMOR(lower(STRAIN)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINKEY_lwr on ZSTG_MAPPINGABSTUMOR(lower(STRAINKEY)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_STRAINGENN_lwr on ZSTG_MAPPINGABSTUMOR(lower(STRAINGENNOTE)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_MTBTUMORID_lwr on ZSTG_MAPPINGABSTUMOR(lower(MTBTUMORID_FILLER)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_AVAILABILI_lwr on ZSTG_MAPPINGABSTUMOR(lower(AVAILABILITY_ID)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_NAME_lwr on ZSTG_MAPPINGABSTUMOR(lower(NAME)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_NOMENCLATU_lwr on ZSTG_MAPPINGABSTUMOR(lower(NOMENCLATURE_ID)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_ABSCANCERM_lwr on ZSTG_MAPPINGABSTUMOR(lower(ABSCANCERMODELID)) PARALLEL NOLOGGING tablespace CAMOD;
create index ZSTG_UMOR_MTBTUMORID_lwr on ZSTG_MAPPINGABSTUMOR(lower(MTBTUMORID)) PARALLEL NOLOGGING tablespace CAMOD;

EXIT;
